2024-10-23 17:50:27.414320: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 17:50:27.461063: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 17:50:27.461443: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-23 17:50:28.988852: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-10-23 17:50:31.155267: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-10-23 17:50:31.155313: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: a100-5
2024-10-23 17:50:31.155319: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: a100-5
2024-10-23 17:50:31.155385: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 535.129.3
2024-10-23 17:50:31.155402: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 535.129.3
2024-10-23 17:50:31.155408: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:309] kernel version seems to match DSO: 535.129.3
2024-10-23 17:50:31.877427: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 17:50:31.926079: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 17:50:31.926465: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-23 17:50:32.941493: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/groups/dlmrimnd/jacob/projects/Segis-Net/code/Segis-Net/Train_SegisNet.py", line 5, in <module>
    from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, CSVLogger
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/__init__.py", line 3, in <module>
    from keras import __internal__
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/__internal__/__init__.py", line 3, in <module>
    from keras.__internal__ import backend
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/__init__.py", line 21, in <module>
    from keras.src import models
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/models/__init__.py", line 18, in <module>
    from keras.src.engine.functional import Functional
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/engine/functional.py", line 25, in <module>
    from keras.src import backend
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/backend/__init__.py", line 10, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/utils/__init__.py", line 53, in <module>
    from keras.src.utils.feature_space import FeatureSpace
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/utils/feature_space.py", line 20, in <module>
    from keras.src.engine import base_layer
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/engine/base_layer.py", line 32, in <module>
    from keras.src import constraints
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/constraints/__init__.py", line 4, in <module>
    from keras.src.constraints.constraints import Constraint
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/constraints/constraints.py", line 2, in <module>
    from keras.src import ops
  File "/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/ops/__init__.py", line 5, in <module>
    from keras.src.backend import cast
ImportError: cannot import name 'cast' from partially initialized module 'keras.src.backend' (most likely due to a circular import) (/home/groups/dlmrimnd/jacob/miniconda3/envs/segis-new-env/lib/python3.9/site-packages/keras/src/backend/__init__.py)
